commit_changelog: true
comment_changelog: true
generate_changelog_using: commit_message
header_prefix: 'Release:'
version_regex: 'v?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})\s\(\d{1,2}-\d{1,2}-\d{4}\)'
pull_request_title_regex: ^Release
group_config:
  - title: Bug Fixes
    labels:
      - bug
      - bugfix
  - title: Improvements to Code
    labels:
      - improvements
      - enhancement
  - title: New Features
    labels:
      - feature
  - title: Documentation Updates
    labels:
      - docs
      - documentation
      - doc
