name: Python application

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: python -m pip install --upgrade pip
    - run: pip install Django==3.2.9
    - run: django-admin startproject mysite .
    - run: nohup python manage.py runserver 0.0.0.0:8080 &

    - name: screenshot
      uses: saadmk11/comment-website-screenshot@main
      with:
        upload_to: github_branch
        capture_changed_html_files: yes
        capture_urls: 'http://172.17.0.1:8080, http://172.17.0.1:8080/admin/login'
