name: test test
on:
  push:
    branches: [ master, dev-65 ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Set Image Tag'
        required: false

defaults:
  run:
    shell: bash

jobs:
  push-image:
    name:  test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bbbbbbbb
        id: build-i
        env:
          IMAGE_TAG: ${{ github.event.inputs.image_tag || github.sha }}
        run: |
          echo "::set-output name=image::$IMAGE_TAG"
