name: Capture Screenshot

on:
  pull_request:
    types: [opened, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: screenshot
        uses: saadmk11/comment-website-screenshot@main
        with:
          upload_to: github_branch
          capture_changed_html_files: yes
          capture_html_file_paths: 'html/about.html,'
          capture_urls: 'https://www.google.com, https://www.twitter.com'
